### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dmittrey** [dmittrey/low-level-programming#1]
- [x] Debug file update tests
- [ ] Implement find method in sect with Iterator
- [ ] Implement find method in file
- [ ] Add state recovery after app reboot
- [ ] Add UserApi
- [ ] Cmake
- [ ] Readme
- [ ] Report
